[build]
  # Diretório de publicação
  publish = "."
  
  # Comando de build (não necessário para arquivos estáticos)
  command = "echo 'No build required for static files'"

[build.environment]
  # Versão do Node.js (se necessário)
  NODE_VERSION = "18"

# Configurações de redirecionamento
[[redirects]]
  from = "/*"
  to = "/fabrica-naie.html"
  status = 200
  conditions = {Role = ["admin"]}

# Configurações de headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para arquivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Headers específicos para arquivos CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Headers específicos para arquivos HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

# Configurações de cache
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configurações para PWA (se implementado no futuro)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"